### ISSUE TITLE
The main GUI isn't loaded successfully

### ISSUE THREAD

**Issue by diaowinner** [kreativekorp/bitsnpicas#29]
I installed the latest Bits'n'Picas, but when I run it, the GUI is like full of crap.

![V_}HEUQ$PM` QHYGM~LQT(F](https://user-images.githubusercontent.com/32033700/185083448-20cbb926-cb64-4a6d-b09b-c82722b1a34d.png)

Both Windows and Linux, and through Eclipse or using the `make` command cause the same effect. In Eclipse, there's the log when I'm clicking the left area in the main window.
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.kreative.bitsnpicas.edit.GlyphListModel.getIconGroup()" because the return value of "com.kreative.bitsnpicas.edit.GlyphListModelList$GlyphListModelTreeNode.getModel()" is null
	at com.kreative.bitsnpicas.edit.glmlicon.GLMLTreeCellRenderer.getImageForTreeCell(GLMLTreeCellRenderer.java:52)
	at com.kreative.bitsnpicas.edit.glmlicon.GLMLTreeCellRenderer.getTreeCellRendererComponent(GLMLTreeCellRenderer.java:35)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3223)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:555)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:189)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:680)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:673)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paintVerticalPartOfLeg(BasicTreeUI.java:1655)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1372)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
But few days ago I even compiled a version that doesn't have this problem. Why would it happens, and what should I do?

**Comment by RebeccaRGB** [comment]
Thanks for the report. This should be fixed now.

**Comment by diaowinner** [comment]
OK. I'll rebuild it soon.

**Comment by diaowinner** [comment]
![](https://user-images.githubusercontent.com/32033700/185346191-19189830-df9e-4a1f-bd91-720f6ad40317.png)
It finally works. Thanks.
